# Generated by Django 4.1.2 on 2023-06-18 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenC', models.ImageField(null=True, upload_to='Carrusel')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=50)),
                ('mensaje', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenD', models.ImageField(null=True, upload_to='DetalleF')),
                ('nombreDF', models.CharField(max_length=30)),
                ('precioDF', models.IntegerField()),
                ('nombreP', models.CharField(max_length=100)),
                ('tamano', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('disponible', models.BooleanField()),
                ('envio', models.CharField(max_length=15)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='figura.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Figuras',
            fields=[
                ('id_figura', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('imagenP', models.ImageField(null=True, upload_to='Figuras')),
                ('imagenF', models.ImageField(null=True, upload_to='Figuras')),
                ('nombreF', models.CharField(max_length=20)),
                ('precioF', models.IntegerField()),
                ('detalle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='figura.detallef')),
            ],
        ),
        migrations.AddField(
            model_name='detallef',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='figura.material'),
        ),
    ]
